name: End-to-end Visual Testing 
on:
  push:
    branches: [ main ]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload screenshots to argos-ci.com
        run: npx @argos-ci/cli upload ./cypress/screenshots

